server {
    listen 80;
    server_name eduro.eastasia.cloudapp.azure.com localhost;

    location / {
        root /home/azureuser/crawler/frontend/public;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
        proxy_pass http://localhost:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /recommendations {
        proxy_pass http://localhost:8000/recommendations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /scholarships {
        proxy_pass http://localhost:8000/scholarships;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /upload-document/ {
        proxy_pass http://localhost:8000/upload-document/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
